export const RouteEnum = {
  HOME: "/",
  PAGE_ONE: "/page1",
  // DASHBOARD: "/",
  // LOGIN: "/login",
  // SIGNUP: "/complete-signUp",
  DASHBOARD: "/dashboard",
  WAREHOUSE: "/warehouse",
  STOCK_MANAGEMENT: "/warehouse/stock-management",
  STOCK_RELEASE: "/warehouse/stock-release",
  ALARM: "/warehouse/alarm",
  INVENTORY: "/inventory",
  ITEMS_MANAGEMENT: "/inventory/items-management",
  STOCK_TAKING: "/inventory/stock-taking",
  INVENTORIES: "/inventory/inventories",

  SHIPMENT: "/shipment",

  SYSTEM_ADMIN: "/system-admin",
  USER_RIGHTS: "/system-admin/user-rights",
  SYSTEM_SETTINGS: "/system-admin/system-settings",
  GENERAL_ADMIN: "/system-admin/general-admin",

  DASHBOARD_REPORTS: "/dashboard-reports",
  GENERAL_REPORTS: "/dashboard-reports/general-reports",
  INVENTORY_REPORTS: "/dashboard-reports/inventory-reports",
  LOGS: "/dashboard-reports/logs",
  DOCUMENTATION_SUPPORT: "/documentation",

  STOCK_INTAKE: "/stock-intake",
  STOCK_DELIVERIES: "/stock-deliveries",
  STOCK_TAGGING: "/stock-tagging",
  PENDING_STOCK: "/pending-stock",
  STOCK_RETURN: "/stock-return",

  MATERIAL_ISSUANCE: "/material-issuance",
  PARTIAL_ISSUANCE: "/partial-issueance",
  MATERIAL_ACCEPTANCE: "/material-acceptance",
  ISSUANCE__CANCELLATION: "/issuance-cancellation",
  ILLEGAL_MOVEMENT_CHART: "/illegal-movement",
  USER_CREATION: "/user-creation",
  ITEM_CREATION: "/item-creation",
  PRODUCT_RACK: "/product-rack",

  USER_MANAGEMENT: "/user-management",

  GLOBAL_BIN: "/global-bin",
  STOCK_BALANCE_SKU: "/stock-balance-SKU",

  STOCK_BALANCE_BY_LOCATION: "/stock-balance-location",
  PRODUCT_BALANCE: "/product-balance",
  AUDIT_LOGS: "/audit-logs",
  TRANSACTION_LOGS: "/tranaction-logs",
  STOCK_BALANCE_RACK: "/stock-balance-rack",
  RECEIVING_LOG: "/receiving-log",
  RELEASE_LOG: "/release-log",

  STOCK_OUTBOUNDS: "/material-issuance",
  STOCK_INTAKE: "/stock-intake",
  STOCK_REQUISITION: "/requisition",
  RACKS: "/racks",
  CONFIRM_RELEASE: "/confirm-release",
};
